### PR TITLE
34 all vocabs endpoint

### PR DESCRIPTION
**Pull request by sroertgen**

### CODE REVIEW

**Comment by sroertgen** [comment]
@phu Please deploy this branch to our test system.

**Comment by Phu2** [comment]
Deployed https://reconcile-test.skohub.io/vocabs
No additional apache config needed as all incoming requests are proxied unchanged.

**Comment by sroertgen** [comment]
@acka47 We now have an endpoint to view all currently uploaded vocabularies for reconciliation with links to their service manifests: https://reconcile-test.skohub.io/vocabs

**Comment by phu** [comment]
> @phu Please deploy this branch to our test system.

FYI, this is not the username you are looking for. ;)

**Review by acka47 — APPROVED** [review]
+1

**Pull request merged**
